export * from './Registration';
export * from './Passport';
export * from './Login';
export * from './InfoBlock';
export * from './ResetPassword';
export * from './BaseModal';
export * from './SimpleInfo';
export * from './OrderSim';
export * from './RegistrationSmall';